### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lguariento** [KitWallace/XQuery-Wikibook#10]
Hello, I'm not sure this is the correct channel for this kind of things (let me know which channel is more appropriate, in case). The 'execute' links on https://en.wikibooks.org/wiki/XQuery/HTML_Table_View (i.e. http://www.cems.uwe.ac.uk/xmlwiki/empTable.xq) are dead.

Luca

**Comment by KitWallace** [comment]
Hi Luca

This link is one of the many listed in issue 6 Dead links where all such links are listed, so this is a duplicate.
